### ISSUE TITLE
Pony Playground doen't update for 

### ISSUE THREAD

**Issue by Dhruv-mak** [ponylang/pony-playground#268]
Hi,
The pony playground doesn't update after making any changes. Here's the link to the playground: https://playground.ponylang.io/?gist=c9a683a0e53926227b4414aa3b33e277
I'ts stuck to the default code. Here's my system specifications.
OS: Arch Linux x86_64 
Host: Strix 15 GL503GE 1.0 
Kernel: 6.11.1-arch1-1
Browser : Firefox Browser 131.0 (64-bit)

**Comment by mfelsche** [comment]
The playground, doesn't automatically update its URL, when the text is updated.
What it does is creating a gist, when hitting the "Share" button and setting creating a permalink to the current state of the playground in the right "result" area. Share this URL instead of the current one in the address bar.

Do you think it would be more intuitive, if the playground were showing the following behaviour:

Upon hitting the "Share" button, the current URL in the address-bar switches to the one created for the current t state.

**Comment by Dhruv-mak** [comment]
I'm not sure if I understood correctly, but I think the gist itself is not getting updated. Current behavior is that even after updating the code, both the `permalink` and `github gist` has the old content when it was first clicked.

**Comment by SeanTAllen** [comment]
@mfelsche I think there is an actual bug right now. See https://ponylang.zulipchat.com/#narrow/stream/189934-general/topic/Playground.20broken.3F

**Comment by SeanTAllen** [comment]
@mfelsche I can replicate this bug.

**Comment by Dhruv-mak** [comment]
@SeanTAllen It is updating every time I click on share. Thanks.
